[colors.primary]
foreground = "#bfbdb6"
background = "#000000"

[colors.cursor]
text = "#0b0e14"
cursor = "#bfbdb6"

[colors.selection]
text = "#bfbdb6"
background = "#1b3a5b"

[colors.normal]
black = "#1e232b"
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"
blue = "#53bdfa"
magenta = "#cda1fa"
cyan = "#90e1c6"
white = "#c7c7c7"

[colors.bright]
black = "#686868"
red = "#f07178"
green = "#aad94c"
yellow = "#ffb454"
blue = "#59c2ff"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#ffffff"
